import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
export const spaceGrotesk = Space_Grotesk({ weight: ['300', '400', '700'], subsets: ['latin'] });
export const metadata = {
  title: "Dextar Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <main >
          <div className={`min-h-screen flex flex-col w-full px-4 flex flex-col m-auto md:px-0 sm:w-[92%] md:w-[86%] lg:w-3/4`}>
            <NavBar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
